### PR TITLE
allow specifying extra files

### PR DESCRIPTION
**Pull request by stchang**

### CODE REVIEW

**Comment by LeifAndersen** [comment]
Eeep, I should point out that this violates the design principle of doodle, which is, god damn it I'm sick of the amount of dumb configuration options scribble has I just want to build a paper damn it so just type in raco doodle and it should all (mostly) work.

I will accept this, but I will probably also change it eventually to have extra files by default too.

**Comment by stchang** [comment]
To be honest, I dont understand how this package helps. It made it even harder to compile the paper. Arent you just hiding the parameters as hardcoded parameters? Isnt that what a makefile is for?

**Comment by LeifAndersen** [comment]
Not quite no. I've hardcoded the parameters yes, but to specific files, and than made a raco doodle new command to set up the files. Its kind of very shitty I agree with you there, but it follows the same design that Rails does.

I'm not saying I agree with the Rails convention over configuration design, I'm just saying that with the world we're stuck in, that model works (for papers).

**Comment by LeifAndersen** [comment]
Of course, it has all of the same problems that the rails philosophy has, like, the moment you want to brea the convention all shit goes loose. But I don't have a good way to avoid that here, as that seems to also be a problem with scribble.

Basically, long story short, raco doodle is supposed to negate the need for a Makefile. Its only there because MF wanted one.

**Pull request merged**
